name: Build

run-name: Build Code

on:
  push:
    branches: ['main']
  schedule:
    - cron: '20 23 28 04 *'

permissions:
  contents: write

concurrency:
  group: 'build'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Hide Editor
        if: github.event.schedule == '20 23 28 04 *'
        run: echo 'VITE_SHOWTIME=true' > .env

      - name: Build App
        run: |
          npm ci
          npm run build
          cd .vitepress/dist
          touch .nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .vitepress/dist # The folder the action should deploy.
